/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.5.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

val localPropertiesFile = file("local.properties")
if (!localPropertiesFile.exists()) {
    val userHome = System.getProperty("user.home")
    val candidateSdkDirs = listOfNotNull(
        System.getenv("ANDROID_HOME"),
        System.getenv("ANDROID_SDK_ROOT"),
        userHome?.let { "$it/Android/Sdk" },
        userHome?.let { "$it/Library/Android/sdk" },
        userHome?.let { "$it/AppData/Local/Android/Sdk" },
    )

    candidateSdkDirs
        .firstOrNull { file(it).isDirectory }
        ?.let { sdkDir ->
            localPropertiesFile.writeText("sdk.dir=${sdkDir.replace("\\", "\\\\")}\n")
        }
}

rootProject.name = "waterfall"
include(":app")
